# Base configs
baseurl: "https://timnault.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Tim Nault"
subtitle: "Black and White Photography by Tim Nault"
author: "Tim Nault"
header:
 title: "Photography"
 subtitle: "by Tim Nault"
footer:
 name: "Tim nault"
 bio: "A self-taught creative making black and white photographic artwork with compositions containing architecture, abstracts, urban scenes, and the natural world."
# github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/timnault/photography\">fork me on github</a> ;)"
#web_design: "Tim Nault"
social_urls:
# <<<<<<< HEAD
  facebook: "https://www.facebook.com/Tim-Nault-Photography-210182339107581/"
  twitter: "https://twitter.com/timnault"
  instagram: "https://www.instagram.com/timnaultphotography/"
  linkedin: "https://www.linkedin.com/in/timnault/"
  github: "https://www.github.com/timnault"
theme: jekyll-theme-minimal
# >>>>>>> 08aad4d1d3754cd7ce4e034cbcb6c10e38eda585
